DROP TABLE IF EXISTS GAMERESULTS;
CREATE TABLE GAMERESULTS (GAMENUM INT, USER TEXT, ANSWERS text, ATTEMPTS INT, PRIMARY KEY (GAMENUM, USER));
INSERT INTO GAMERESULTS (USER, GAMENUM, ANSWERS, ATTEMPTS) VALUES ('lettucebowler', 286, 'ixcixiixxixxxxx', 3);