name = "api-wordlettuce"
compatibility_date = "2023-01-01"

[[ d1_databases ]]
binding = "WORDLETTUCE_DB"
database_name = "wordlettuce"
database_id = "293cfa38-9bea-49f1-862c-dc033cf4fa2e"


[env.prod]
routes = [
  { pattern = "api.word.lettucebowler.net", custom_domain = true }
]