name = "api-wordlettuce"
main = "src/index.ts"
compatibility_date = "2022-12-08"

d1_databases = [
  { binding = "WORDLETTUCE_DB", database_id="293cfa38-9bea-49f1-862c-dc033cf4fa2e", database_name = "wordlettuce", preview_database_id = "dc9d6725-0526-4a87-9cc0-a06b6c31a4de"}
]

[env.prod]
routes = [
  { pattern = "api.word.lettucebowler.net", custom_domain = true, zone_name = "lettucebowler.net" }
]

