name = "api-wordlettuce"
compatibility_date = "2023-05-18"

[[ d1_databases ]]
binding = "WORDLETTUCE_DB"
database_name = "wordlettuce-beta"
database_id = "6f4b4e21-8961-4fe3-b2da-842499b37879"


[env.prod]
routes = [
  { pattern = "api.word.lettucebowler.net", custom_domain = true }
]